CREATE DATABASE BANK;
USE BANK;

CREATE TABLE CUSTOMER
(ACCNO INT(5) PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(25),
ADDRESS VARCHAR(25),
TELLNO INT(10),
DOP DATE,
ACCTYPE VARCHAR(15)
)AUTO_INCREMENT=1000;

CREATE TABLE BNKTRANSACTION
(ACCNO INT(5),
DOT DATE,
TTYPE VARCHAR(2),
TAMT FLOAT(10,3),
BALANCE FLOAT(10,3));

/* To view the structure of the tables use this  

DESCRIBE TABLENAME;

*/


